services:
    web:
        build:
            context: ./src
            dockerfile: Dockerfile.prod
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
        volumes:
            - static_volume:/home/warden/www/polimerbeton/staticfiles
        expose:
            - 8000
        env_file:
            - ./env/.env.staging
        depends_on:
            - db

    db:
        image: postgres:17.6
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./env/.env.staging.db

    nginx-proxy:
        build: ./web/nginx
        container_name: nginx-proxy
        restart: always
        ports:
            - 443:443
            - 80:80
        volumes:
            - static_volume:/home/warden/www/polimerbeton/staticfiles
            - certs:/etc/nginx/certs:rw
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            # - conf:/etc/nginx/conf.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - web

    acme-companion:
        image: nginxproxy/acme-companion:2.6
        container_name: nginx-proxy-acme
        env_file:
            - ./env/.env.staging.proxy-companion
        volumes:
            - acme:/etc/acme.sh
            - certs:/etc/nginx/certs:rw
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            # - conf:/etc/nginx/conf.d
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - nginx-proxy

volumes:
    postgres_data:
    static_volume:
    acme:
    certs:
    html:
    vhost:
    # conf:
