services:
    web:
        build: ./src
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./src/:/www/polimerbeton/src/
        ports:
            - 8000:8000
        env_file:
            - ./env/.env.dev
        depends_on:
            - db

    db:
        image: postgres:17.6
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=dummy_guy
            - POSTGRES_PASSWORD=dummy_guy_password
            - POSTGRES_DB=polimerbeton_db

volumes:
    postgres_data:
