services:
    web:
        build:
            context: ./src
            dockerfile: Dockerfile.prod
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
        volumes:
            - static_volume:/home/warden/www/polimerbeton/staticfiles
        expose:
            - 8000
        env_file:
            - ./env/env/.env.prod
        depends_on:
            - db

    db:
        image: postgres:17.6
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./env/.env.prod.db

    nginx:
        build: ./web/nginx
        ports:
            - 1337:80
        volumes:
            - static_volume:/home/warden/www/polimerbeton/staticfiles
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
