services:
    web:
        build:
            context: ./src
            dockerfile: Dockerfile.prod
        image: polimerbeton-web:latest
        container_name: polimerbeton-web
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
        restart: always
        volumes:
            - static_volume:/home/warden/www/polimerbeton/staticfiles:z
        expose:
            - 8000
        env_file:
            - ./env/.env.prod
        depends_on:
            - db

    db:
        image: postgres:17.6
        container_name: polimerbeton-db
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/:Z
        env_file:
            - ./env/.env.prod.db

    nginx-proxy:
        build:
            context: ./web/nginx/nginx-proxy
            dockerfile: Dockerfile.prod
        container_name: nginx-proxy
        restart: always
        ports:
            - 443:443
            - 80:80
        volumes:
            - static_volume:/home/warden/www/polimerbeton/staticfiles:z
            - conf:/etc/nginx/conf.d:z
            - vhost:/etc/nginx/vhost.d:z
            - html:/usr/share/nginx/html:z
            - certs:/etc/nginx/certs:z,ro
            - /var/run/docker.sock:/tmp/docker.sock:z,ro
        depends_on:
            - web

    docker-gen:
        image: nginxproxy/docker-gen:0.15
        container_name: docker-gen
        restart: always
        command: -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - ./web/nginx/nginx-proxy/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:Z,ro
            - conf:/etc/nginx/conf.d:z
            - vhost:/etc/nginx/vhost.d:z
            - html:/usr/share/nginx/html:z
            - certs:/etc/nginx/certs:z,ro
            - /var/run/docker.sock:/tmp/docker.sock:z,ro

    acme-companion:
        image: nginxproxy/acme-companion:2.6
        container_name: acme-companion
        restart: always
        env_file:
            - ./env/.env.prod.proxy-companion
        volumes:
            - conf:/etc/nginx/conf.d:z
            - vhost:/etc/nginx/vhost.d:z
            - html:/usr/share/nginx/html:z
            - certs:/etc/nginx/certs:z,rw
            - acme:/etc/acme.sh:Z
            - /var/run/docker.sock:/var/run/docker.sock:z,ro
        depends_on:
            - nginx-proxy

networks:
    default:
        name: polimerbeton-app-network-prod-selinux

volumes:
    postgres_data:
    static_volume:
    acme:
    certs:
    html:
    vhost:
    conf:
