# Generated by Django 5.1 on 2024-08-31 17:20

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Client ID')),
                ('last_name', encrypted_model_fields.fields.EncryptedCharField(default='нет фамилии', verbose_name='Last Name')),
                ('first_name', encrypted_model_fields.fields.EncryptedCharField(default='нет имени', verbose_name='First Name')),
                ('middle_name', encrypted_model_fields.fields.EncryptedCharField(null=True, verbose_name='Middle Name')),
                ('phone_number', encrypted_model_fields.fields.EncryptedCharField(default='нет телефона', unique=True, verbose_name='Phone')),
                ('privacy_policy_agree', encrypted_model_fields.fields.EncryptedBooleanField(default=False, verbose_name='The client agrees with the privacy policy')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'unique_together': {('phone_number',)},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Request ID')),
                ('request_number_for_this_client', models.PositiveIntegerField(default=1, verbose_name='Request number for this client')),
                ('date_time_registration_for_this_request', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of registration for this request')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main_app.client', verbose_name='Client ID')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'db_table': 'requests',
                'unique_together': {('client_id', 'request_number_for_this_client')},
            },
        ),
    ]
