# Generated by Django 5.1 on 2024-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_number_for_this_client',
            field=models.PositiveIntegerField(default=0, verbose_name='Request number for this client'),
        ),
    ]
