# Generated by Django 5.1 on 2024-09-01 13:58

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Available attempt count'),
        ),
        migrations.AddField(
            model_name='client',
            name='block_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Blocked until'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(default='нет имени', verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(default='нет фамилии', verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=encrypted_model_fields.fields.EncryptedCharField(null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(default='нет телефона', verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number_hash',
            field=models.CharField(default='нет хэша телефона', max_length=64, unique=True, verbose_name='Phone number hash'),
        ),
    ]
