# Generated by Django 5.1 on 2024-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_client_attempt_count_client_block_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='attempt_count',
        ),
        migrations.AddField(
            model_name='client',
            name='attempts_available',
            field=models.IntegerField(default=3, verbose_name='Attempts available'),
        ),
    ]
