# Generated by Django 5.1 on 2024-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_client_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='attempts_available',
            field=models.PositiveIntegerField(default=3, verbose_name='Attempts available'),
        ),
    ]
