# Generated by Django 5.1 on 2024-09-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_client_attempts_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='block_until',
            new_name='blocked_until',
        ),
        migrations.RemoveField(
            model_name='client',
            name='attempts_available',
        ),
        migrations.AddField(
            model_name='client',
            name='available_attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='Available attempts'),
        ),
    ]
